# Generated by Django 4.1.7 on 2023-04-22 16:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='hangmanWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=50)),
                ('category', models.CharField(blank=True, max_length=100, null=True)),
                ('meaning', models.TextField()),
                ('difficulty', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='hangman_Game',
            fields=[
                ('answer', models.CharField(max_length=50)),
                ('guessed', models.CharField(blank=True, max_length=26, null=True)),
                ('status', models.CharField(default='IN_PROGRESS', max_length=20)),
                ('game_id', models.AutoField(primary_key=True, serialize=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
