# Generated by Django 4.1.7 on 2023-04-22 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hangmanGame', '0002_alter_hangman_game_game_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hangman_game',
            name='game_id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False),
        ),
    ]
