# Generated by Django 4.1.7 on 2023-04-22 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hangmanGame', '0003_alter_hangman_game_game_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hangman_game',
            name='guessed',
            field=models.CharField(default='', max_length=26),
        ),
    ]
