# Generated by Django 4.1.7 on 2023-04-24 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hangmanGame', '0005_hangman_game_difficulty'),
    ]

    operations = [
        migrations.AddField(
            model_name='hangman_game',
            name='mode',
            field=models.CharField(default='', max_length=20),
        ),
    ]
